spring:
  application:
    name: starter
  data:
    # MongoDB configuration
    mongodb:
      host: localhost
      port: 27017
      database: starter
      username: admin
      password: password
      authentication-database: admin
    # Redis configuration
    redis:
      host: localhost
      port: 6379
  # Kafka configuration
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: starter-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    template:
      default-topic: test-topic

logging:
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSS'Z'} %clr(%5p) [%thread] %clr(%logger{40}){cyan} : %msg%n"
  timezone: UTC
  level:
    root: INFO
  ansi:
    enabled: ALWAYS
